    version: '2'

    services:
      jekyll:
        image: btquanto/docker-jekyll
        ports:
          - 4000:4000
        volumes:
          - ./:/src
        command: jekyll serve -H 0.0.0.0 --draft